version: '3'
services:
  front:
    build: ./front
    container_name: real-time-chat-front
    volumes:
      - ./front:/usr/src/app
    ports:
      - 3000:3000
  server:
    build: ./server
    container_name: real-time-chat-server
    volumes:
      - ./server:/app
    ports:
      - 3001:3001
    depends_on:
      - db
  db:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: db    
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: