"""create table

Revision ID: 272edf091624
Revises: 3bd5a17501d6
Create Date: 2023-06-04 12:04:33.363201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272edf091624'
down_revision = '3bd5a17501d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dones')
    op.drop_table('tasks')
    # ### end Alembic commands ###
