"""Create Table

Revision ID: 9f8c988db224
Revises: 
Create Date: 2023-06-09 12:35:12.434817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9f8c988db224"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    room_table = op.create_table(
        "room",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    user_table = op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    chat_table = op.create_table(
        "chat",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["room.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        user_table,
        [
            {
                "name": "田中 太郎",
                "created_at": "2023-06-09 00:00:00",
                "updated_at": "2023-06-09 00:00:00",
            },
            {
                "name": "山田 花子",
                "created_at": "2023-06-09 00:00:00",
                "updated_at": "2023-06-09 00:00:00",
            },
        ],
    )
    op.bulk_insert(
        room_table,
        [
            {
                "name": "打ち合わせ",
                "created_at": "2023-06-09 00:00:00",
                "updated_at": "2023-06-09 00:00:00",
            },
        ],
    )
    op.bulk_insert(
        chat_table,
        [
            {
                "room_id": 1,
                "user_id": 1,
                "message": "よろしくお願いします。",
                "created_at": "2023-06-09 00:00:00",
                "updated_at": "2023-06-09 00:00:00",
            },
            {
                "room_id": 1,
                "user_id": 2,
                "message": "こちらこそ、よろしくお願いします。",
                "created_at": "2023-06-09 00:00:00",
                "updated_at": "2023-06-09 00:00:00",
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat")
    op.drop_table("user")
    op.drop_table("room")
    # ### end Alembic commands ###
